server:
  port: 8086
  servlet:
    context-path: /ressources

spring:
  application:
    name: RessourcesMS

  cloud:
    config:
      enabled: true
      uri: http://localhost:8088
      import-check:
        enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    username: Aya
    password:
    url: jdbc:h2:file:./Database/Data/Ressource
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: pidevlearn1@gmail.com
    password: bjbxyxkejdcwhuiq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liwijTRICMFwC04x
            client-secret: f49e64a6b0af92417ebb489459292ef07374c89f
            scope:
              - read:user
              - user:email
          google:
            client-id: 1014911445366-g14b42h60261a3ie6lcrrv2k7t6jpa69.apps.googleusercontent.com
            client-secret: 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

  app:
    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwtExpirationMs: 172800000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

file:
  upload-dir: uploads

frontend:
  url: http://localhost:4200

user-auth-service:
  url: http://localhost:8081

google:
  gemini:
    api-key: AIzaSyByCJ-3bmDXIiQYzVuGbbXReKcpkxsGFII

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent
